//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://com/iex/Messages", ClrNamespace="com.iex.Messages")]

namespace com.iex.Messages
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokeredMessage", Namespace="http://com/iex/Messages")]
    public partial class BrokeredMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BodyJsonField;
        
        private string MessageTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyJson
        {
            get
            {
                return this.BodyJsonField;
            }
            set
            {
                this.BodyJsonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://com/iex", ConfigurationName="IBrokeredMessageService")]
public interface IBrokeredMessageService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com/iex/IBrokeredMessageService/Submit", ReplyAction="http://com/iex/IBrokeredMessageService/SubmitResponse")]
    com.iex.Messages.BrokeredMessage Submit(com.iex.Messages.BrokeredMessage message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://com/iex/IBrokeredMessageService/Submit", ReplyAction="http://com/iex/IBrokeredMessageService/SubmitResponse")]
    System.Threading.Tasks.Task<com.iex.Messages.BrokeredMessage> SubmitAsync(com.iex.Messages.BrokeredMessage message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBrokeredMessageServiceChannel : IBrokeredMessageService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BrokeredMessageServiceClient : System.ServiceModel.ClientBase<IBrokeredMessageService>, IBrokeredMessageService
{
    
    public BrokeredMessageServiceClient()
    {
    }
    
    public BrokeredMessageServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BrokeredMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BrokeredMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BrokeredMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public com.iex.Messages.BrokeredMessage Submit(com.iex.Messages.BrokeredMessage message)
    {
        return base.Channel.Submit(message);
    }
    
    public System.Threading.Tasks.Task<com.iex.Messages.BrokeredMessage> SubmitAsync(com.iex.Messages.BrokeredMessage message)
    {
        return base.Channel.SubmitAsync(message);
    }
}
